modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="skippy_tools"
version="1.0.0"
displayName="Skippy Tools"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="CPR, MCreator"

[[dependencies.skippy_tools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




